name = "OPEN Kaposvár"
license = "Apache License 2.0"
licenselink = "//github.com/openkaposvar/hugo-openkaposvar-theme/blob/master/LICENSE"
description = "Theme for our official website."
homepage = "//github.com/openkaposvar/hugo-openkaposvar"
tags = ["community", "open"]
features = ["responsive", "portfolio", "substitutable strings"]
min_version = 0.14

[author]
  name = "OPEN Kaposvár"
  homepage = "//github.com/openkaposvar"

# If porting an existing theme
[original]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"
  repo = "//github.com/digitalcraftsman/hugo-creative-theme"
