baseurl = "http://openkaposvar.github.io/"
languageCode = "hu"
title = "OPEN Kaposvár"
theme = "hugo-openkaposvar-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "OPEN Kaposvár"
	description = "Nyílt megoldásokkal egy okosabb Kaposvárért"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Font Awesome embed code (see: http://fontawesome.io/get-started/)
	fontawesomeCode = "XXXXXXXXXX"
	# Navigation
	[params.navigation]
		brand = "OPEN Kaposvár"

		[params.navigation.links]
			about     = "Rólunk"
			services  = "Célkitűzéseink"
			portfolio = "Projektjeink"
			contact   = "Kapcsolat"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Nyílt megoldásokkal egy okosabb Kaposvárért"
		subtitle   = "Projektjeink megoldást kínálunk az itt élők problémáira, vagy éppen könnyebbé, jobbá teszik a mindennapjaikat."
		buttonText = "Tudj meg többet rólunk"


	# About section
	[params.about]
		headline    = "Kik vagyunk?"
		description = "[Civil hackerek](http://nol.hu/kulfold/a-hacker-ahol-tud-segit-1524621) - javarészt programozók, akik szabadidejükben olyan eszközökön törik a fejüket, amelyek a közösség javát szolgálják. Szoftvereket írunk, szolgáltatásokat hozunk létre, adatokat szerzünk be, gyártunk és teszünk közzé."
		buttonText  = "Szállj be te is!"


	# Service section
	[params.services]
		headline = "Célkitűzéseink"

  [[params.services.list]]
      icon = "fa-eye"
      title = "Transzparencia"
      description = "A folyamatos kommunikáció hívei vagyunk. Akármin is dolgozunk, igyekszünk a lehető legkorábban megosztani azt a közösséggel. Ez garantálja, hogy valóban hasznos eszközöket alkothassunk."

  [[params.services.list]]
			icon = "fa-universal-access"
			title = "Hozzáférhetőség"
			description = "Sokat dolgozunk rajta, hogy eszközeinket bárki korlátok nélkül használhassa."

		[[params.services.list]]
      icon = "fa-recycle"
      title = "Folyamatosság"
      description = "Korábbi munkáinkról sem feledkezünk meg. Minden projektnek kerítünk valakit, aki jó gazda módjára gondozza, felügyeli azt. Ebben különösen számítunk a közösség erejére!"

    [[params.services.list]]
        icon = "fa-users"
        title = "Közösséget alkotni"
        description = "Az OPEN Kaposvár nem csak a szoftverekről és az adatokról szól. Kiemelt célunk egy okos és aktív közösség létrehozása."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Az összes projekt szabadon felhasználható, módosítható"

		[params.aside.button]
			text = "Irány a GitHub!"
			link = "//github.com/openkaposvar"

	# Contact section
	[params.contact]
		headline = "Lépj kapcsolatba velünk!"
		description = "Van egy jó ötleted, ami jobbá tehetné az emberek életét? Észrevételed van a munkánkkal kapcsolatban? Remek! Keress fel minket!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
